apiVersion: v1
kind: Service
metadata:
  labels:
    env: {{ .Values.environment }}
  name: {{ .Release.Name }}-{{ .Values.environment }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: poc
  selector:
    app: {{ .Release.Name }}
    env: {{ .Values.environment }}
  type: NodePort
